version: '3.3'
services:
  backend:
      container_name: backend
      restart: always
      build: 
        context: .
        dockerfile: server.dockerfile
      image: santa
      env_file:
        - docker.env
      networks:
        - mysql
      working_dir: /app
      ports:
      - '${PORT}:${PORT}'
  db:
    image: mysql:5.7
    restart: always
    networks:
      - mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      
networks:
  mysql:
    driver: bridge

volumes:
  my-db: